# Generated by Django 4.0.2 on 2022-02-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mpmUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('organism', models.CharField(choices=[('XXXXX', 'PlantCyc'), ('XXXX', 'BrachyCyc'), ('XXX', 'SolCyc')], max_length=5)),
                ('canopus_predictions', models.FileField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
    ]
