# Generated by Django 4.0.2 on 2022-02-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpmUpload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpmupload',
            name='name',
        ),
    ]
