# Generated by Django 4.0.2 on 2022-02-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpmUpload', '0002_remove_mpmupload_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpmupload',
            name='organism',
            field=models.CharField(choices=[('PlantCyc', 'PlantCyc'), ('BrachyCyc', 'BrachyCyc'), ('SolCyc', 'SolCyc')], max_length=10),
        ),
    ]
